### ISSUE TITLE
Push 0.0.4 to Forge

### ISSUE THREAD

**Issue by 3flex** [ripienaar/puppet-module-data#17]
I see 0.0.4 is tagged in Github, but it's not on the Forge yet.

**Comment by ripienaar** [comment]
Closing this as the module is now unsupported and known to break Puppet 4.

Puppet 4 has this feature natively and you should use that.  See https://www.devco.net/archives/2016/01/08/native-puppet-4-data-in-modules.php

A release have been made that complains if you use it on Puppet 4, a follow up release will refuse to work at all.
