### ISSUE TITLE
module_data incompatible with puppet 3.4.0

### ISSUE THREAD

**Issue by janorn** [ripienaar/puppet-module-data#2]
Your module requires 'puppet/indirector/hiera'. This is gone in puppet 3.4.0.

It has been included in puppet/indirector/code. Have tried to rename it but doesn't seem to work.

**Comment by ripienaar** [comment]
Closing this, you should move to the native puppet 4 feature

https://www.devco.net/archives/2016/01/08/native-puppet-4-data-in-modules.php
