### ISSUE TITLE
Hiera merging defaulting to native

### ISSUE THREAD

**Issue by tamarintech** [ripienaar/puppet-module-data#25]
Configuration exists in several yaml files that I would like to merge together.

When using hiera.yaml with merge_behavior: deeper the expected behavior happens.
If I move merge_behavior: deeper out of the top level hiera.yaml and into the module's data/hiera.yaml the behavior defaults to native merging.  I would like my module to be independent of global configuration and be able to function with the merge_behavior specified within the module.

I have put together a sort of hacky fix that loads the module's merged config and then replaces it before the key is returned here: https://github.com/tamarintech/puppet-module-data/commit/8e30018d2455bb13de655ee8fa6def960a53ebd7

I'm not sure that is the ideal way to go about changing Hiera's merge_behavior to deeper.

**Comment by ripienaar** [comment]
hiera just doesnt support this today.  Seems hiera is being rewritten for puppet 4 by puppet labs to be able to do this - so that they can achieve other goals.

For today you just cant do it :(

Your solution is likely to break badly on multi threaded ruby web servers :)

**Comment by tamarintech** [comment]
Yea, the Hiera::Config.load approach seems pretty terrible.

I guess the only other approach if I wanted this now would be to re-implement deeper merge within module_data?

**Comment by ripienaar** [comment]
yeah i guess, but I doubt I'd merge that :)

**Comment by tamarintech** [comment]
Understood. :+1:
