### ISSUE TITLE
[QUESTION] Is it possible to use this module to provide included class defaults ?

### ISSUE THREAD

**Issue by mickaelperrin** [ripienaar/puppet-module-data#32]
Hi,

I am currently writing "meta" modules that aggregates various modules by theme (security, monitoring, defaults, backup...).

I would like to store those defaults in hiera. Can I use this module to do that ?

It seems that the settings are searched directly in the hiera files attached to the node and then fall back directly to the hiera files associated with the included module. The "meta" module is skipped.

I tried several patterns, like inherits or composition but I didn't succeed.

Any hints ?

Thanks again,

Mickaël

**Comment by ripienaar** [comment]
```
include meta_module

$foo = $meta_module::foo
```

that should fetch data from the meta module and if $foo on it was a class parameter it would be sourced from that modules hiera
