### ISSUE TITLE
Puppet 4 warning has broken my environment...

### ISSUE THREAD

**Issue by fatmcgav** [ripienaar/puppet-module-data#34]
Updating this module to 615bc91fc18e5c8ee658876137dba86a30281f73 seems to have broken all the Data module lookups on our Puppet 3.7.5 master... 

Will try and get some more debug output in due course, however wanted to get an early warning out there for others...

**Comment by ripienaar** [comment]
ok thanks for the headsup, details of how it broke it would be useful!

**Comment by fatmcgav** [comment]
Symptom wise, I was seeing lots of:
> Error 400 on SERVER: Must pass param to Class[class] 

for params that were previously binding from module data.. 

Will run up a local Puppet Master and try and debug the issue and update...

**Comment by ripienaar** [comment]
hmm, That is weird! can you run it with --trace on?

**Comment by celebdor** [comment]
@ripienaar: The same happened to my module.

Here ran with trace:
`[1;31mError: Must pass midonet_thirdparty_repo to Class[Midonet::Repository] at /tmp/manifest.pp:25 on node juju-machine-2-lxc-4.maas
/usr/lib/ruby/vendor_ruby/puppet/util/errors.rb:97:in `fail'
/usr/lib/ruby/vendor_ruby/puppet/resource.rb:440:in `block in validate_complete'
/usr/lib/ruby/vendor_ruby/puppet/resource.rb:438:in `each'
/usr/lib/ruby/vendor_ruby/puppet/resource.rb:438:in `validate_complete'
/usr/lib/ruby/vendor_ruby/puppet/resource/type.rb:304:in `set_resource_parameters'
/usr/lib/ruby/vendor_ruby/puppet/resource/type.rb:107:in `evaluate_code'
/usr/lib/ruby/vendor_ruby/puppet/parser/resource.rb:79:in `evaluate'
/usr/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:198:in `block in evaluate_classes'
/usr/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:183:in `each'
/usr/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:183:in `evaluate_classes'
/usr/lib/ruby/vendor_ruby/puppet/parser/ast/resource.rb:60:in `block (3 levels) in evaluate'
/usr/lib/ruby/vendor_ruby/puppet/util/errors.rb:62:in `exceptwrap'
/usr/lib/ruby/vendor_ruby/puppet/parser/ast/resource.rb:43:in `block (2 levels) in evaluate'
/usr/lib/ruby/vendor_ruby/puppet/parser/ast/resource.rb:42:in `collect'
/usr/lib/ruby/vendor_ruby/puppet/parser/ast/resource.rb:42:in `block in evaluate'
/usr/lib/ruby/vendor_ruby/puppet/parser/ast/branch.rb:12:in `block in each'
/usr/lib/ruby/vendor_ruby/puppet/parser/ast/branch.rb:11:in `each'
/usr/lib/ruby/vendor_ruby/puppet/parser/ast/branch.rb:11:in `each'
/usr/lib/ruby/vendor_ruby/puppet/parser/ast/resource.rb:25:in `collect'
/usr/lib/ruby/vendor_ruby/puppet/parser/ast/resource.rb:25:in `evaluate'
/usr/lib/ruby/vendor_ruby/puppet/parser/ast.rb:62:in `safeevaluate'
/usr/lib/ruby/vendor_ruby/puppet/parser/ast/block_expression.rb:15:in `block in evaluate'
/usr/lib/ruby/vendor_ruby/puppet/parser/ast/block_expression.rb:10:in `each'
/usr/lib/ruby/vendor_ruby/puppet/parser/ast/block_expression.rb:10:in `evaluate'
/usr/lib/ruby/vendor_ruby/puppet/parser/ast.rb:62:in `safeevaluate'
/usr/lib/ruby/vendor_ruby/puppet/resource/type.rb:121:in `evaluate_code'
/usr/lib/ruby/vendor_ruby/puppet/parser/resource.rb:79:in `evaluate'
/usr/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:366:in `evaluate_main'
/usr/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:110:in `block in compile'
/usr/lib/ruby/vendor_ruby/puppet/util/profiler/none.rb:6:in `profile'
/usr/lib/ruby/vendor_ruby/puppet/util/profiler.rb:31:in `profile'
/usr/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:110:in `compile'
/usr/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:23:in `compile'
/usr/lib/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:116:in `block (2 levels) in compile'
/usr/lib/ruby/vendor_ruby/puppet/util/profiler/none.rb:6:in `profile'
/usr/lib/ruby/vendor_ruby/puppet/util/profiler.rb:31:in `profile'
/usr/lib/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:114:in `block in compile'
/usr/lib/ruby/vendor_ruby/puppet/util.rb:161:in `block in benchmark'
/usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/usr/lib/ruby/vendor_ruby/puppet/util.rb:160:in `benchmark'
/usr/lib/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:113:in `compile'
/usr/lib/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:46:in `find'
/usr/lib/ruby/vendor_ruby/puppet/indirector/indirection.rb:201:in `find'
/usr/lib/ruby/vendor_ruby/puppet/application/apply.rb:204:in `main'
/usr/lib/ruby/vendor_ruby/puppet/application/apply.rb:146:in `run_command'
/usr/lib/ruby/vendor_ruby/puppet/application.rb:364:in `block (2 levels) in run'
/usr/lib/ruby/vendor_ruby/puppet/application.rb:470:in `plugin_hook'
/usr/lib/ruby/vendor_ruby/puppet/application.rb:364:in `block in run'
/usr/lib/ruby/vendor_ruby/puppet/util.rb:478:in `exit_on_fail'
/usr/lib/ruby/vendor_ruby/puppet/application.rb:364:in `run'
/usr/lib/ruby/vendor_ruby/puppet/util/command_line.rb:137:in `run'
/usr/lib/ruby/vendor_ruby/puppet/util/command_line.rb:91:in `execute'
/usr/bin/puppet:4:in `<main>'[0m
[1;31mError: Must pass midonet_thirdparty_repo to Class[Midonet::Repository] at /tmp/manifest.pp:25 on node juju-machine-2-lxc-4.maas
/usr/lib/ruby/vendor_ruby/puppet/util/errors.rb:97:in `fail'
/usr/lib/ruby/vendor_ruby/puppet/resource.rb:440:in `block in validate_complete'
/usr/lib/ruby/vendor_ruby/puppet/resource.rb:438:in `each'
/usr/lib/ruby/vendor_ruby/puppet/resource.rb:438:in `validate_complete'
/usr/lib/ruby/vendor_ruby/puppet/resource/type.rb:304:in `set_resource_parameters'
/usr/lib/ruby/vendor_ruby/puppet/resource/type.rb:107:in `evaluate_code'
/usr/lib/ruby/vendor_ruby/puppet/parser/resource.rb:79:in `evaluate'
/usr/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:198:in `block in evaluate_classes'
/usr/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:183:in `each'
/usr/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:183:in `evaluate_classes'
/usr/lib/ruby/vendor_ruby/puppet/parser/ast/resource.rb:60:in `block (3 levels) in evaluate'
/usr/lib/ruby/vendor_ruby/puppet/util/errors.rb:62:in `exceptwrap'
/usr/lib/ruby/vendor_ruby/puppet/parser/ast/resource.rb:43:in `block (2 levels) in evaluate'
/usr/lib/ruby/vendor_ruby/puppet/parser/ast/resource.rb:42:in `collect'
/usr/lib/ruby/vendor_ruby/puppet/parser/ast/resource.rb:42:in `block in evaluate'
/usr/lib/ruby/vendor_ruby/puppet/parser/ast/branch.rb:12:in `block in each'
/usr/lib/ruby/vendor_ruby/puppet/parser/ast/branch.rb:11:in `each'
/usr/lib/ruby/vendor_ruby/puppet/parser/ast/branch.rb:11:in `each'
/usr/lib/ruby/vendor_ruby/puppet/parser/ast/resource.rb:25:in `collect'
/usr/lib/ruby/vendor_ruby/puppet/parser/ast/resource.rb:25:in `evaluate'
/usr/lib/ruby/vendor_ruby/puppet/parser/ast.rb:62:in `safeevaluate'
/usr/lib/ruby/vendor_ruby/puppet/parser/ast/block_expression.rb:15:in `block in evaluate'
/usr/lib/ruby/vendor_ruby/puppet/parser/ast/block_expression.rb:10:in `each'
/usr/lib/ruby/vendor_ruby/puppet/parser/ast/block_expression.rb:10:in `evaluate'
/usr/lib/ruby/vendor_ruby/puppet/parser/ast.rb:62:in `safeevaluate'
/usr/lib/ruby/vendor_ruby/puppet/resource/type.rb:121:in `evaluate_code'
/usr/lib/ruby/vendor_ruby/puppet/parser/resource.rb:79:in `evaluate'
/usr/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:366:in `evaluate_main'
/usr/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:110:in `block in compile'
/usr/lib/ruby/vendor_ruby/puppet/util/profiler/none.rb:6:in `profile'
/usr/lib/ruby/vendor_ruby/puppet/util/profiler.rb:31:in `profile'
/usr/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:110:in `compile'
/usr/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:23:in `compile'
/usr/lib/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:116:in `block (2 levels) in compile'
/usr/lib/ruby/vendor_ruby/puppet/util/profiler/none.rb:6:in `profile'
/usr/lib/ruby/vendor_ruby/puppet/util/profiler.rb:31:in `profile'
/usr/lib/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:114:in `block in compile'
/usr/lib/ruby/vendor_ruby/puppet/util.rb:161:in `block in benchmark'
/usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/usr/lib/ruby/vendor_ruby/puppet/util.rb:160:in `benchmark'
/usr/lib/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:113:in `compile'
/usr/lib/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:46:in `find'
/usr/lib/ruby/vendor_ruby/puppet/indirector/indirection.rb:201:in `find'
/usr/lib/ruby/vendor_ruby/puppet/application/apply.rb:204:in `main'
/usr/lib/ruby/vendor_ruby/puppet/application/apply.rb:146:in `run_command'
/usr/lib/ruby/vendor_ruby/puppet/application.rb:364:in `block (2 levels) in run'
/usr/lib/ruby/vendor_ruby/puppet/application.rb:470:in `plugin_hook'
/usr/lib/ruby/vendor_ruby/puppet/application.rb:364:in `block in run'
/usr/lib/ruby/vendor_ruby/puppet/util.rb:478:in `exit_on_fail'
/usr/lib/ruby/vendor_ruby/puppet/application.rb:364:in `run'
/usr/lib/ruby/vendor_ruby/puppet/util/command_line.rb:137:in `run'
/usr/lib/ruby/vendor_ruby/puppet/util/command_line.rb:91:in `execute'
/usr/bin/puppet:4:in `<main>'[0m`

**Comment by celebdor** [comment]
Perhaps more readable here:
http://paste.ubuntu.com/15200144/

**Comment by ripienaar** [comment]
OK this makes more sense - the one from @fatmcgav I see now was anonymised and made no sense to me :)

what version puppet are you 2 on?

**Comment by celebdor** [comment]
@ripienaar 3.4.3 Ubuntu 14.04.3 lts

**Comment by fatmcgav** [comment]
@ripienaar Sorry about the anon, should have made it a bit clearer... 

Was in the process of running a local master in debug mode but got side tracked... 

Am running 3.7.5 under Passenger... 

Cheers 
Gav

**Comment by ripienaar** [comment]
great, should have been a noop for you! So perhaps my version detection logic is busted, do you get the warning logged about it being deprecated?

**Comment by celebdor** [comment]
@ripienaar asking me?

**Comment by ripienaar** [comment]
I mean this commit should have not changed a thing for you - but I also realised there are some older commits in here that wasnt released.

@celebdor if you can see if you're getting the warnings? or @fatmcgav it would be the same for either of you

**Comment by celebdor** [comment]
@ripienaar: Full output of --trace and --debug
http://paste.ubuntu.com/15200356/

I see no warning there

**Comment by ripienaar** [comment]
Great thank you, leave it with me I'll see if I can reproduce here

**Comment by fatmcgav** [comment]
@ripienaar will check my logs in the morning, however don't recall seeing any warnings... 

Also, rolling back to the previous commit (aa537833) fixes things for me, so I'm fairly confident it's the commit referenced specifically... 

Cheers

**Comment by celebdor** [comment]
@ripienaar let me know if there is anything else I can provide you. I'll still be online for 3h today

**Comment by ripienaar** [comment]
@celebdor in your example where do you have `midonet::repository::midonet_thirdparty_repo` defined? In what data file?

**Comment by celebdor** [comment]
@ripienaar /etc/puppet/modules/midonet/data/osfamily/Debian/common.yaml

**Comment by celebdor** [comment]
@ripienaar https://github.com/openstack/puppet-midonet/blob/master/data/osfamily/Debian/common.yaml

**Comment by ripienaar** [comment]
@celebdor oh this is pretty lame, please try this patch https://github.com/ripienaar/puppet-module-data/pull/35

I somehow messed up moving this code from my test environment where I was committing the code - my test environment still worked till I diffed the released one and what I was testing!

**Comment by fatmcgav** [comment]
Ah, one line makes all the difference... :-) 

Will give it a go in the morning, unless @celebdor beats me to it...

**Comment by celebdor** [comment]
@ripienaar fixed it. you can go ahead with 0.5.1 ;-) Thanks a lot for the quick support!

**Comment by ripienaar** [comment]
Done, thanks a lot for the help in fixing it, such a rookie mistake!

**Comment by fatmcgav** [comment]
Cheers for the quick fix @ripienaar and for the debug assist @celebdor...

**Comment by celebdor** [comment]
;-)
